name: Deploy Vue.js Application to Production Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Synchronize Files To Server
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        script: cd "/var/www/Vue-Task-Management-App && ./.scripts/deploy.sh" 

