name: Deploy Vue.js Application to Production Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install NPM Dependencies
      run: npm install

    - name: Build NPM Assets (Vue.js)
      run: npm run build

    - name: Debug Info
      run: |
        echo "Workspace directory:"
        pwd
        echo "Files in directory:"
        ls -la

    - name: Synchronize Files To Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "./dist"
        REMOTE_HOST: ${{ secrets.VPS_HOST }}
        REMOTE_USER: ${{ secrets.VPS_USER }}
        TARGET: "/var/www/Vue-Task-Management-App"
